// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rad.roo.document.domain;

import org.rad.roo.document.domain.DocumentRelationship;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DocumentRelationship_Roo_Configurable {
    
    declare @type: DocumentRelationship: @Configurable;
    
}
