package org.rad.modul;

public enum DocumentRelationshipType {
			REFERSTO,BASEDON,COPYOF,VARIANTOF,TRANSLATIONOF,DECOMPOSITIONOF,
			SUBSTITUIONOF, DERIVATIONOF, AFFECTION, ADDITIONTO, PEERTO, 
			SEQUENCETO, WITHDRAWALOF, SUPERSEDING, SUPERSEDEDBY, DOCUMENTSETPART

}
